version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: musashi-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - musashi-dev-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: musashi-backend-dev
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/musashi?authSource=admin
      DATABASE_NAME: musashi
      SECRET_KEY: dev-secret-key
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - musashi-dev-network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    container_name: musashi-mcp-dev
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      CONTEXT7_MAX_TOKENS: 100000
      THINKING_MODEL: claude-3-sonnet-20240229
    ports:
      - "3001:3001"
    volumes:
      - ./mcp:/app/mcp
    networks:
      - musashi-dev-network

volumes:
  mongodb_dev_data:

networks:
  musashi-dev-network:
    driver: bridge