# Simple Kubernetes Deployment for Musashi
# Minimal deployment configuration for Musashi AI Agent Workflow Design Tool
---
apiVersion: v1
kind: Namespace
metadata:
  name: musashi
  labels:
    app: musashi
---
# Musashi Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musashi
  namespace: musashi
  labels:
    app: musashi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: musashi
  template:
    metadata:
      labels:
        app: musashi
    spec:
      containers:
      - name: musashi
        image: ghcr.io/iml1111/musashi:v1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: frontend
          protocol: TCP
        - containerPort: 8080
          name: backend
          protocol: TCP
        env:
        # MongoDB connection - replace with your MongoDB instance
        - name: MONGODB_URL
          value: "mongodb://your-mongodb-host:27017/musashi"
        # JWT secret key - generate your own secure key
        - name: SECRET_KEY
          value: "your-secret-key-must-be-32-characters-minimum"
        - name: DATABASE_NAME
          value: "musashi"
        - name: BACKEND_CORS_ORIGINS
          value: "http://localhost,https://your-domain.com"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "11520"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# Horizontal Pod Autoscaler (optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musashi-hpa
  namespace: musashi
  labels:
    app: musashi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musashi
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80