name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password123
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install ruff
    
    - name: Lint backend
      run: |
        cd backend
        ruff check .
    
    - name: Test backend
      run: |
        cd backend
        python -m pytest
      env:
        MONGODB_URL: mongodb://admin:password123@localhost:27017/musashi_test?authSource=admin
        DATABASE_NAME: musashi_test
        SECRET_KEY: test-secret-key

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint frontend
      run: |
        cd frontend
        npm run lint
    
    - name: Test frontend
      run: |
        cd frontend
        npm run test:coverage
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Build Docker images
      run: |
        docker compose build
    
    - name: Test Docker compose up
      env:
        SECRET_KEY: test-secret-key-for-ci
        MONGODB_URL: mongodb://mongo:27017
        DATABASE_NAME: musashi_test
      run: |
        # Start services
        docker compose up -d
        
        # Wait for containers to be ready
        echo "Waiting for containers to start..."
        sleep 30
        
        # Check container status
        docker compose ps
        
        # Check logs
        echo "=== Mongo logs ==="
        docker compose logs mongo | tail -10
        echo "=== App logs ==="
        docker compose logs musashi | tail -20
        
        # Test MongoDB connection first
        if docker compose exec -T mongo mongosh --quiet --eval "db.runCommand('ping')" 2>/dev/null; then
          echo "MongoDB is responding"
        else
          echo "MongoDB is not responding"
        fi
        
        # Try connecting to app
        echo "Testing app connectivity..."
        timeout 30 bash -c 'until docker compose exec -T musashi curl -sf http://localhost:8080/api/v1/health; do sleep 2; done' || {
          echo "App health check failed, trying alternative check..."
          docker compose exec -T musashi curl -v http://localhost:8080/ || echo "Direct connection failed"
        }
        
        # Cleanup
        docker compose down